#!/usr/bin/env bash

# Delete first 22 characters
request=${1:22}

# Decode URL
request=$(echo $request | echo -e "$(sed 's/+/ /g; s/%/\\x/g')")

# Replace &line= with :
request=${request/&line=/:}

# Replace &column= with :
request=${request/&column=/:}

# Launch Atom
atom $request
