#!/usr/bin/env bash

# Getting the file url
request=$(echo $1 | echo -e "$(sed 's/^.*file:\/\///')")

# Decode URL
request=$(echo $request | echo -e "$(sed 's/+/ /g; s/%/\\x/g')")

# Replace &line= with :
request=${request/&line=/:}

# Replace &column= with :
request=${request/&column=/:}

# Launch Atom
atom $request
